[features]
seeds = true
skip-lint = false
[programs.localnet]
anchor_nft_staking = "9zezsu8xLYtPfAkWue3vB9NBTkFX2iMGpcetsDTnTLHy"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "Localnet"
cluster = "devnet"
wallet = "/home/srmq/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
